# Site settings
title: Portfolio Projects Website
description: My individual projects related to Data Analytics and Data Sciences

# GitHub Pages settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

google_analytics: [Your Google Analytics tracking ID]
