theme: jekyll-theme-minimal
# Site settings
title: Portfolio Projects
author:
  name: Tito Dwi Syahputra
  email: your-email@domain.com
description: "Data Science Projects"

# Build settings
remote_theme: jekyll/minima
