title: Portfolio Projects Website
author:
  name: Tito Dwi Syahputra
  email: titodwi20@gmail.com
description: My individual projects related to Data Analytics and Data Sciences

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:  
  social_links:
    - { platform: github,         user_url: "https://github.com/dstito" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/tito-dwi-syahputra/" }

# remote_theme: jekyll/minima
