title: Portfolio Projects
author:
  name: Tito Dwi Syahputra
  email: titodwi20@gmail.com
description: Tito's projects related to Data Analytics and Data Sciences

minima:
  social_links:
    - { platform: github,         user_url: 'https://github.com/dstito' }
    - { platform: linkedin,       user_url: 'https://www.linkedin.com/in/tito-dwi-syahputra' }
google_analytics: G-272GE5PKCW
remote_theme: jekyll/minima
