title: Portfolio Projects Website
author:
  name: Tito Dwi Syahputra
  email: titodwi20@gmail.com
description: My individual projects related to Data Analytics and Data Sciences
linkedin_username: tito-dwi-syahputra
remote_theme: jekyll/minima
