title: Portfolio Projects Website
description: My individual projects related to Data Analytics and Data Sciences
author:
  name: Tito Dwi Syahputra
  email: titodwi20@gmail.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
- { platform: linkedin, user_url: "https://www.linkedin.com/in/jekyll" }
